### ISSUE TITLE
Commands need additional explaination.

### ISSUE THREAD

**Issue by codecnotsupported** [h33p/scanflow#5]
I haven't read scanflow's code, but I'm confused how to use certain commands.
Is it all explained in the [memflow applied playlist](https://www.youtube.com/watch?v=xJXkRMy71dc&list=PLrC4R7zDrxB17iWCy9eEdCaluCR3Bkn8q)?

### Self explanatory:
`quit q: quit the CLI`
`help h: show this help`
`reset r: reset all context state`

`add a: manually add an address to matches`
`remove rm: remove match by index`
`print p: print found matches after initial scan`

### Needs additional info
`write wr: write values to select matches. Arguments: {idx/*} {o/c} {value}`
- {idx/*}
    - `idx`: Write to the search match idx.
    - `*`: Write to the all search matches. (I'd prefer `all` as oppose to `*`)
- {o/c}
    - `o`: No clue
    - `c`: No clue
- value: Self explainitory
------
`reinterpret ri: reinterpret matches as another type. Usage: {{type}} ({{unsized len}})`
- {{type}} 
    - Target recast type: `str, str_utf16, i8, u8, i16, u16, i32, u32, i64, u64, i128, u128, f32, f64`
- ({{unsized len}})
    - Optional: Size of the type, Applicable to `str` and `str_utf16`
- NOTE: Why the double {{}} brackets?
------
`globals g: find all global variables referenced by code`
- No idea how to use.
- What the use of it is.
------
`sigmaker s: build a pointer map. args: {addr}`
- No idea how to use.
------
`offset_scan os: scan for offsets to matches. Arguments: {y/[n]} {lower range} {upper range} {max depth} ({filter})`
- {y/[n]} 
    - y/n??
    - Default = n
- {lower range} 
    - scan result ptr - lower range = lower range 
- {upper range} 
    - scan result ptr - upper range = upper range 
- {max depth} 
    - Derefence pointers? And scan those?
- ({filter})
    - Optional: A Filter??
------
`pointer_map pm: build a pointer map`
- No idea how to use. ( I know what a pointer map is )
- Note: This caused a BSOD: `watchdog timeout` in the VM, further causing a unresponsive host system, sysrq-reboot still worked, this will probably work with other (not `qemu`) connectors.
    - Might be caused due to improper usage.

**Comment by codecnotsupported** [comment]
# I watched the series, it explains it fairly well.
## Updated explanation (Please update the help command)
### Self explanatory:
`quit q: quit the CLI`
`help h: show this help`
`reset r: reset all context state`

`add a: manually add an address to matches`
`remove rm: remove match by index`
`print p: print found matches after initial scan`

### Additional info
`write wr: write values to select matches. Arguments: {idx/*} {o/c} {value}`
- {idx/*}
    - `idx`: Write to the search match idx.
    - `*`: Write to the all search matches. (I'd prefer `all` as oppose to `*`)
- {o/c}
    - `o`: Write once.
    - `c`: Spawn thread and continuously write.
- value: Self explanatory
------
`reinterpret ri: reinterpret matches as another type. Usage: {{type}} ({{unsized len}})`
- {{type}} 
    - Target recast type: `str, str_utf16, i8, u8, i16, u16, i32, u32, i64, u64, i128, u128, f32, f64`
- ({{unsized len}})
    - Optional: Size of the type, Applicable to `str` and `str_utf16`
- NOTE: Why the double {{}} brackets?
------
`globals g: find all global variables referenced by code`
- Finds globals in target process' binary, no purpose as it is automatically done when using Offset scan.
------
`sigmaker s: build a pointer map. args: {addr}`
- Usage: After using offset scan, take the first hex value of the result you want, and sigmaker will produce a signature which you can scan for.
------
`offset_scan os: scan for offsets to matches. Arguments: {y/[n]} {lower range} {upper range} {max depth} ({filter})`
- {y/[n]} 
    - y: Use disassembler to find instructions in binary to refer to globals.
    - n: use the whole binary?
    - Default = n
- {lower range} 
    - scan_result_ptr - lower range 
- {upper range} 
    - scan_result_ptr + upper range
    - `[scan_result_ptr - lower range, scan_result_ptr + upper range]  = scan area`
- {max depth} 
    - max scan depth
- ({filter})
    - Optional: Filter address (hex)
- Explanation: Finds a pointer chains from the binary to the scan results.

------
`pointer_map pm: build a pointer map`
- Re-builds pointer map, (used in `offset_scan`)-
- Done automatically in `offset_scan`
- Not too useful. Unless you know that the binary changed somehow.

**Comment by h33p** [comment]
Added in https://github.com/memflow/scanflow/commit/5813d5fcd89f8b3b98852daa11f6fb26c6c556d1

**Comment by h33p** [comment]
Thank you so much! Apologies for being so late.
